### ISSUE TITLE
Replace OpenSSL with ring?

### ISSUE THREAD

**Issue by satoshinm** [Thinkofname/steven#67]
Hi, I'm very interested in trying out steven but having some trouble getting it to build, wondering if anyone has had success on macOS Sierra? I installed [rustup](https://www.rustup.rs) and updated to  rustc 1.19.0-nightly (e17a1227a 2017-05-12), but am getting errors about openssl-sys-extra 0.7.14:

```
steven $ cargo build
   Compiling openssl-sys-extras v0.7.14
   Compiling openssl v0.7.14
   Compiling num-rational v0.1.35
error: failed to run custom build command for `openssl-sys-extras v0.7.14`
process didn't exit successfully: `/tmp/steven/target/debug/build/openssl-sys-extras-68e943a43ac25314/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("1")
PROFILE = Some("debug")
TARGET = Some("x86_64-apple-darwin")
debug=true opt-level=1
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O1" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-I" "/usr/local/include" "-o" "/tmp/steven/target/debug/build/openssl-sys-extras-e60f1107e2e04baa/out/src/openssl_shim.o" "-c" "src/openssl_shim.c"
cargo:warning=src/openssl_shim.c:132:7: error: incomplete definition of type 'struct dh_st'
cargo:warning=    dh->p = p;
cargo:warning=    ~~^
cargo:warning=/usr/local/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'struct dh_st'
cargo:warning=typedef struct dh_st DH;
cargo:warning=               ^
cargo:warning=src/openssl_shim.c:133:7: error: incomplete definition of type 'struct dh_st'
cargo:warning=    dh->g = g;
cargo:warning=    ~~^
cargo:warning=/usr/local/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'struct dh_st'
cargo:warning=typedef struct dh_st DH;
cargo:warning=               ^
cargo:warning=src/openssl_shim.c:134:7: error: incomplete definition of type 'struct dh_st'
cargo:warning=    dh->q = q;
cargo:warning=    ~~^
cargo:warning=/usr/local/include/openssl/ossl_typ.h:104:16: note: forward declaration of 'struct dh_st'
cargo:warning=typedef struct dh_st DH;
cargo:warning=               ^
cargo:warning=src/openssl_shim.c:143:13: error: incomplete definition of type 'struct x509_st'
cargo:warning=    return x->cert_info ? x->cert_info->extensions : NULL;
cargo:warning=           ~^
cargo:warning=/usr/local/include/openssl/ossl_typ.h:119:16: note: forward declaration of 'struct x509_st'
cargo:warning=typedef struct x509_st X509;
cargo:warning=               ^
cargo:warning=src/openssl_shim.c:143:28: error: incomplete definition of type 'struct x509_st'
cargo:warning=    return x->cert_info ? x->cert_info->extensions : NULL;
cargo:warning=                          ~^
cargo:warning=/usr/local/include/openssl/ossl_typ.h:119:16: note: forward declaration of 'struct x509_st'
cargo:warning=typedef struct x509_st X509;
cargo:warning=               ^
cargo:warning=5 errors generated.
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread 'main' panicked at 'explicit panic', /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.35/src/lib.rs:897
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl v0.7.14`
process didn't exit successfully: `/tmp/steven/target/debug/build/openssl-58434463ef6b42e5/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("1")
PROFILE = Some("debug")
TARGET = Some("x86_64-apple-darwin")
debug=true opt-level=1
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O1" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-I" "/usr/local/include" "-o" "/tmp/steven/target/debug/build/openssl-56b1b41302837114/out/src/c_helpers.o" "-c" "src/c_helpers.c"
cargo:warning=src/c_helpers.c:4:5: warning: implicit declaration of function 'CRYPTO_add' is invalid in C99 [-Wimplicit-function-declaration]
cargo:warning=    CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=    ^
cargo:warning=src/c_helpers.c:4:20: error: incomplete definition of type 'struct ssl_st'
cargo:warning=    CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=                ~~~^
cargo:warning=/usr/local/include/openssl/ossl_typ.h:144:16: note: forward declaration of 'struct ssl_st'
cargo:warning=typedef struct ssl_st SSL;
cargo:warning=               ^
cargo:warning=src/c_helpers.c:4:37: error: use of undeclared identifier 'CRYPTO_LOCK_SSL'
cargo:warning=    CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=                                    ^
cargo:warning=src/c_helpers.c:8:20: error: incomplete definition of type 'struct ssl_ctx_st'
cargo:warning=    CRYPTO_add(&ctx->references,1,CRYPTO_LOCK_SSL_CTX);
cargo:warning=                ~~~^
cargo:warning=/usr/local/include/openssl/ossl_typ.h:145:16: note: forward declaration of 'struct ssl_ctx_st'
cargo:warning=typedef struct ssl_ctx_st SSL_CTX;
cargo:warning=               ^
cargo:warning=src/c_helpers.c:8:35: error: use of undeclared identifier 'CRYPTO_LOCK_SSL_CTX'
cargo:warning=    CRYPTO_add(&ctx->references,1,CRYPTO_LOCK_SSL_CTX);
cargo:warning=                                  ^
cargo:warning=src/c_helpers.c:12:21: error: incomplete definition of type 'struct x509_st'
cargo:warning=    CRYPTO_add(&x509->references,1,CRYPTO_LOCK_X509);
cargo:warning=                ~~~~^
cargo:warning=/usr/local/include/openssl/ossl_typ.h:119:16: note: forward declaration of 'struct x509_st'
cargo:warning=typedef struct x509_st X509;
cargo:warning=               ^
cargo:warning=src/c_helpers.c:12:36: error: use of undeclared identifier 'CRYPTO_LOCK_X509'
cargo:warning=    CRYPTO_add(&x509->references,1,CRYPTO_LOCK_X509);
cargo:warning=                                   ^
cargo:warning=1 warning and 6 errors generated.
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread 'main' panicked at 'explicit panic', /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.35/src/lib.rs:897
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: build failed
steven $ 
```

I see openssl 0.7.8 is specified in Cargo.toml, so I tried changing it to: 0.7.14, 0.8.3, and 0.9.12, but https://github.com/sfackler/rust-openssl says "This README does not correspond to rust-openssl 0.7.x or 0.8.x. ", i.e., 0.9.x is completely different (incompatible). 

Searched and found similar errors with 0.7.14 but no solution: 
* https://gist.github.com/andreastt/f5f50cc50e9a5af6c72e6cfb4aeed6f1
* https://pastebin.com/Uzau7Xg2

would it be possible to update steven to rust-openssl 0.9.12? (i'd try to myself but am new to rust, if no one else is interested maybe I'll see what I can do later) 

---

As described on https://github.com/Thinkofname/steven/wiki/Compiling-and-or-running#compiling-on-os-x, I installed openssl 1.0.2k with `brew install openssl` and added `export PATH=/usr/local/opt/openssl/bin:$PATH` to my ~/.bash_profile.

**Comment by satoshinm** [comment]
The problem was the linker/compiler search paths, I was able to fix this error by running:

```sh
CFLAGS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" cargo build
```

**Comment by satoshinm** [comment]
```sh
CFLAGS="-I/usr/local/opt/openssl/include" LDFLAGS="-L/usr/local/opt/openssl/lib" cargo build
```

gets further (after fixing the would_unwrap change, PR incoming), but still can't link - any hints?

```
  = note: Undefined symbols for architecture x86_64:
            "_SSL_library_init", referenced from:
                openssl_sys::init::_$u7b$$u7b$closure$u7d$$u7d$::h2fb4f5b915427582 in libopenssl_sys-234dd3c1920e901d.rlib(openssl_sys-234dd3c1920e901d.0.o)
            "_SSL_load_error_strings", referenced from:
                openssl_sys::init::_$u7b$$u7b$closure$u7d$$u7d$::h2fb4f5b915427582 in libopenssl_sys-234dd3c1920e901d.rlib(openssl_sys-234dd3c1920e901d.0.o)
            "_OPENSSL_add_all_algorithms_noconf", referenced from:
                openssl_sys::init::_$u7b$$u7b$closure$u7d$$u7d$::h2fb4f5b915427582 in libopenssl_sys-234dd3c1920e901d.rlib(openssl_sys-234dd3c1920e901d.0.o)
            "_CRYPTO_set_id_callback", referenced from:
                openssl_sys::set_id_callback::hbdf8d74db3bf6c28 in libopenssl_sys-234dd3c1920e901d.rlib(openssl_sys-234dd3c1920e901d.0.o)
            "_CRYPTO_set_locking_callback", referenced from:
                openssl_sys::init::_$u7b$$u7b$closure$u7d$$u7d$::h2fb4f5b915427582 in libopenssl_sys-234dd3c1920e901d.rlib(openssl_sys-234dd3c1920e901d.0.o)
            "_SSLv23_method", referenced from:
                openssl::ssl::SslMethod::to_raw::hc62ff0ab67b31c68 in libopenssl-97681c4ab867dd44.rlib(openssl-97681c4ab867dd44.0.o)
            "_SSL_CTX_get_ex_new_index", referenced from:
                openssl::ssl::init::_$u7b$$u7b$closure$u7d$$u7d$::ha9b7c32fbf0bd918 in libopenssl-97681c4ab867dd44.rlib(openssl-97681c4ab867dd44.0.o)
            "_EVP_MD_CTX_destroy", referenced from:
                _$LT$openssl..crypto..hash..Hasher$u20$as$u20$core..ops..Drop$GT$::drop::he8352e86fc902880 in libopenssl-97681c4ab867dd44.rlib(openssl-97681c4ab867dd44.0.o)
            "_CRYPTO_num_locks", referenced from:
                openssl_sys::init::_$u7b$$u7b$closure$u7d$$u7d$::h2fb4f5b915427582 in libopenssl_sys-234dd3c1920e901d.rlib(openssl_sys-234dd3c1920e901d.0.o)
            "_EVP_MD_CTX_create", referenced from:
                openssl::crypto::hash::Hasher::new::ha9d4983e118f8968 in libopenssl-97681c4ab867dd44.rlib(openssl-97681c4ab867dd44.0.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by satoshinm** [comment]
Probably not the cleanest way to do this, but I was able to build successfully by copying the dependencies:

```sh
sudo cp -r /usr/local/opt/openssl/lib/* target/debug/deps/
CFLAGS="-I/usr/local/opt/openssl/include" cargo build
```

Note: there are alternative crypto libraries for Rust, https://github.com/rust-unofficial/awesome-rust#cryptography, this one may be a viable alternative for symmetric crypto and hashes: https://github.com/briansmith/ring

**Comment by satoshinm** [comment]
Sorry, I missed the next section https://github.com/Thinkofname/steven/wiki/Compiling-and-or-running#compiling-1 - compiles fine with:

```sh
LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib" OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include OPENSSL_LIB_DIR=`brew --prefix openssl`/lib cargo build --release
```
